### PR TITLE
Support Doctrine ORM 3.0

### PR DESCRIPTION
**Pull request by wmouwen**
Doctrine ORM v3.0.0 has been released.
https://github.com/doctrine/orm/releases/tag/3.0.0

Upgrade the minimal version of the ORM to v2.14, allow v3.0 as well. This matches the version requirement as used by [doctrine/doctrine-fixtures-bundle](https://github.com/doctrine/DoctrineFixturesBundle/blob/6c3253bfd071b57fac9a5b02cd7b1e5b9803148e/composer.json#L26).

Update the GitHub workflows to test against v2.14, v2.18 and v3.0.

### CODE REVIEW

**Comment by wmouwen** [comment]
@chalasr Allow me to tag you here. Could you enable the workflows to run?

**Comment by wmouwen** [comment]
The package `symfony/doctrine-bridge` versions `6.4` and above [conflict](https://github.com/symfony/doctrine-bridge/blob/e4fb1e141b00cee5de8b8a2fe7008301b6b4dabd/composer.json#L55) with `doctrine/orm` version `2.14.*`. Removed those combinations from the GitHub workflows.

Fixed the errors thrown by psalm and php-cs-fixer.

**Comment by abozhinov** [comment]
When to expect the new release?  I've saw that all tests are passed.

**Review by chalasr — APPROVED** [review]
Nice work.

**Comment by chalasr** [comment]
Thank you @wmouwen.

**Pull request merged**
