### PR TITLE
add request token event

### PR DESCRIPTION
**Pull request by jr-k**
I've added an event to manipulate the response during /token process. Useful to add some Set-Cookie directives for example.

### CODE REVIEW

**Review by mtarld — CHANGES_REQUESTED** [review]
Hey @jr-k!

Thanks for your PR :slightly_smiling_face: 

Could you add some unit tests as well?
Moreover, there are some unneeded blank lines that must be removed in order to follow the current coding standards

**Comment by jr-k** [comment]
Some what ? Never heard of "tests". Joke aside, I'm not very good nor familiar at writing tests.

Here is a commit for blank lines.

**Comment by chalasr** [comment]
@jr-k Time to level up then? :)

Jokes aside, thanks for the PR.
If you are wiling to write that test (which will be required for merging anyway), you can probably copy an existing case in `TokenEndpointTest`. Some events close to the one you are introducing are tested there.

Also, some code quality checks of our CI are broken with this change. 
Can you check the failing jobs in the CI? Their output should give you enough info to fix them.

**Comment by jr-k** [comment]
Here we are, no conflict and tests, alright ?

**Review by chalasr — APPROVED** [review]
Perfect 👌

**Comment by jr-k** [comment]
Is there a merge date policy ?

**Comment by chalasr** [comment]
Thank you @jr-k.

**Comment by chalasr** [comment]
Released in https://github.com/thephpleague/oauth2-server-bundle/releases/tag/v0.1.1

**Pull request merged**
