### PR TITLE
feat: config response type class

### LINKED ISSUE #118: Custom BearerTokenResponse / AuthorizationServer
Hello,

how is it possible to use the `getExtraParams` within `BearerTokenResponse` via this bundle?
Seems like it is currently static within Extensions `configureAuthorizationServer`

Thanks!

### PR DESCRIPTION
**Pull request by develth**
fixes #118

### CODE REVIEW

**Comment by icanhazstring** [comment]
Can we get this merged?
I am directly looking for that, so get https://github.com/steverhoades/oauth2-openid-connect-server working.

You can't change the responseType otherwise.

**Comment by chalasr** [comment]
I'm waiting for the `(draft)` to be removed from the PR title :)

**Comment by chalasr** [comment]
Dunno why the GHA builds didn't run though

**Comment by develth** [comment]
> I'm waiting for the `(draft)` to be removed from the PR title :)

Removed it :)
Should I apply the fix by @mrardon or do you add it?

**Comment by chalasr** [comment]
Thanks! 
Given this is open for more than a year, I’ll happily take care of making the change if you don’t (+ rebase to trigger the CI)

**Comment by develth** [comment]
Go for it, i can't do it until tomorrow ✌️👍

**Comment by chalasr** [comment]
Thank you @develth.

**Comment by develth** [comment]
> > And why the laugh @mrardon ?
> 
> @develth Whoops I'm blind lol meant +1 👍. Thanks for this!

Thx, thought i did a bullshit commitit message :D

**Pull request merged**
